name: 编译多个内核
on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "分支"
        required: true
        default: 'sm8475'
      FEIL:
        description: "配置文件"
        required: true
        default: 'oneplus_ace2_v'
      CPUD:
        description: "处理器代号"
        required: true
        default: 'taro'
      ANDROID_VERSION:
        description: "内核安卓版本"
        required: true
        default: 'android12'
      KERNEL_VERSION:
        description: "内核版本"
        required: true
        default: '5.10'
      KERNEL_NAME:
        description: "修改内核名称"
        required: true
        default: '-android12-9-0-g0a04ff961c85'
      kernelsu_variant:
        description: "选择 KSU"
        required: true
        type: choice
        options:
          - Kernel
          - SukiSU
          - SukiSU-Ultra
        default: SukiSU
      kernelsu_version:
        description: "选择 KSU 版本"
        required: true
        type: choice
        options:
          - without ksu
          - tag
          - main
        default: main
      SUSFS_ENABLED:
        description: "添加 SUSFS"
        required: true
        type: boolean
        default: true
      VFS_patch_ENABLED:
        description: "添加 vfs 补丁（新钩子）？"
        required: true
        type: choice
        options:
          - enable
          - disable
        default: enable

jobs:
  build-kernel-ace2:
    uses: ./.github/workflows/ace2.yml
    secrets: inherit
    with:
      CPU: ${{ inputs.CPU }}
      FEIL: ${{ inputs.FEIL }}
      CPUD: ${{ inputs.CPUD }}
      ANDROID_VERSION: ${{ inputs.ANDROID_VERSION }}
      KERNEL_VERSION: ${{ inputs.KERNEL_VERSION }}
      KERNEL_NAME: ${{ inputs.KERNEL_NAME }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_version: ${{ inputs.kernelsu_version }}
      SUSFS_ENABLED: ${{ inputs.SUSFS_ENABLED }}
      VFS_patch_ENABLED: ${{ inputs.VFS_patch_ENABLED }}

  build-kernel-ace2pro:
    uses: ./.github/workflows/ace2pro.yml
    secrets: inherit
    with:
      CPU: ${{ inputs.CPU }}
      FEIL: ${{ inputs.FEIL }}
      CPUD: ${{ inputs.CPUD }}
      ANDROID_VERSION: ${{ inputs.ANDROID_VERSION }}
      KERNEL_VERSION: ${{ inputs.KERNEL_VERSION }}
      KERNEL_NAME: ${{ inputs.KERNEL_NAME }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_version: ${{ inputs.kernelsu_version }}
      SUSFS_ENABLED: ${{ inputs.SUSFS_ENABLED }}
      VFS_patch_ENABLED: ${{ inputs.VFS_patch_ENABLED }}

  build-kernel-ace3:
    uses: ./.github/workflows/ace3.yml
    secrets: inherit
    with:
      CPU: ${{ inputs.CPU }}
      FEIL: ${{ inputs.FEIL }}
      CPUD: ${{ inputs.CPUD }}
      ANDROID_VERSION: ${{ inputs.ANDROID_VERSION }}
      KERNEL_VERSION: ${{ inputs.KERNEL_VERSION }}
      KERNEL_NAME: ${{ inputs.KERNEL_NAME }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_version: ${{ inputs.kernelsu_version }}
      SUSFS_ENABLED: ${{ inputs.SUSFS_ENABLED }}
      VFS_patch_ENABLED: ${{ inputs.VFS_patch_ENABLED }}

  build-kernel-ace3pro:
    uses: ./.github/workflows/ace3Pro.yml
    secrets: inherit
    with:
      CPU: ${{ inputs.CPU }}
      FEIL: ${{ inputs.FEIL }}
      CPUD: ${{ inputs.CPUD }}
      ANDROID_VERSION: ${{ inputs.ANDROID_VERSION }}
      KERNEL_VERSION: ${{ inputs.KERNEL_VERSION }}
      KERNEL_NAME: ${{ inputs.KERNEL_NAME }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_version: ${{ inputs.kernelsu_version }}
      SUSFS_ENABLED: ${{ inputs.SUSFS_ENABLED }}
      VFS_patch_ENABLED: ${{ inputs.VFS_patch_ENABLED }}

  build-kernel-ace3v:
    uses: ./.github/workflows/ace3v.yml
    secrets: inherit
    with:
      CPU: ${{ inputs.CPU }}
      FEIL: ${{ inputs.FEIL }}
      CPUD: ${{ inputs.CPUD }}
      ANDROID_VERSION: ${{ inputs.ANDROID_VERSION }}
      KERNEL_VERSION: ${{ inputs.KERNEL_VERSION }}
      KERNEL_NAME: ${{ inputs.KERNEL_NAME }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_version: ${{ inputs.kernelsu_version }}
      SUSFS_ENABLED: ${{ inputs.SUSFS_ENABLED }}
      VFS_patch_ENABLED: ${{ inputs.VFS_patch_ENABLED }}

  build-kernel-ace5:
    uses: ./.github/workflows/ace5.yml
    secrets: inherit
    with:
      CPU: ${{ inputs.CPU }}
      FEIL: ${{ inputs.FEIL }}
      CPUD: ${{ inputs.CPUD }}
      ANDROID_VERSION: ${{ inputs.ANDROID_VERSION }}
      KERNEL_VERSION: ${{ inputs.KERNEL_VERSION }}
      KERNEL_NAME: ${{ inputs.KERNEL_NAME }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_version: ${{ inputs.kernelsu_version }}
      SUSFS_ENABLED: ${{ inputs.SUSFS_ENABLED }}
      VFS_patch_ENABLED: ${{ inputs.VFS_patch_ENABLED }}

  build-kernel-ace5pro:
    uses: ./.github/workflows/ace5pro整合.yml
    secrets: inherit
    with:
      CPU: ${{ inputs.CPU }}
      FEIL: ${{ inputs.FEIL }}
      CPUD: ${{ inputs.CPUD }}
      ANDROID_VERSION: ${{ inputs.ANDROID_VERSION }}
      KERNEL_VERSION: ${{ inputs.KERNEL_VERSION }}
      KERNEL_NAME: ${{ inputs.KERNEL_NAME }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_version: ${{ inputs.kernelsu_version }}
      SUSFS_ENABLED: ${{ inputs.SUSFS_ENABLED }}
      VFS_patch_ENABLED: ${{ inputs.VFS_patch_ENABLED }}

  build-kernel-oneplus11:
    uses: ./.github/workflows/OnePlus11.yml
    secrets: inherit
    with:
      CPU: ${{ inputs.CPU }}
      FEIL: ${{ inputs.FEIL }}
      CPUD: ${{ inputs.CPUD }}
      ANDROID_VERSION: ${{ inputs.ANDROID_VERSION }}
      KERNEL_VERSION: ${{ inputs.KERNEL_VERSION }}
      KERNEL_NAME: ${{ inputs.KERNEL_NAME }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_version: ${{ inputs.kernelsu_version }}
      SUSFS_ENABLED: ${{ inputs.SUSFS_ENABLED }}
      VFS_patch_ENABLED: ${{ inputs.VFS_patch_ENABLED }}

  build-kernel-oneplus12:
    uses: ./.github/workflows/oneplus12.yml
    secrets: inherit
    with:
      CPU: ${{ inputs.CPU }}
      FEIL: ${{ inputs.FEIL }}
      CPUD: ${{ inputs.CPUD }}
      ANDROID_VERSION: ${{ inputs.ANDROID_VERSION }}
      KERNEL_VERSION: ${{ inputs.KERNEL_VERSION }}
      KERNEL_NAME: ${{ inputs.KERNEL_NAME }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_version: ${{ inputs.kernelsu_version }}
      SUSFS_ENABLED: ${{ inputs.SUSFS_ENABLED }}
      VFS_patch_ENABLED: ${{ inputs.VFS_patch_ENABLED }}

  build-kernel-oneplus12r:
    uses: ./.github/workflows/oneplus12r.yml
    secrets: inherit
    with:
      CPU: ${{ inputs.CPU }}
      FEIL: ${{ inputs.FEIL }}
      CPUD: ${{ inputs.CPUD }}
      ANDROID_VERSION: ${{ inputs.ANDROID_VERSION }}
      KERNEL_VERSION: ${{ inputs.KERNEL_VERSION }}
      KERNEL_NAME: ${{ inputs.KERNEL_NAME }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_version: ${{ inputs.kernelsu_version }}
      SUSFS_ENABLED: ${{ inputs.SUSFS_ENABLED }}
      VFS_patch_ENABLED: ${{ inputs.VFS_patch_ENABLED }}
      
  build-kernel-oneplus13:
     uses: ./.github/workflows/oneplus13整合.yml
     secrets: inherit
     with:
      CPU: ${{ inputs.CPU }}
      FEIL: ${{ inputs.FEIL }}
      CPUD: ${{ inputs.CPUD }}
      ANDROID_VERSION: ${{ inputs.ANDROID_VERSION }}
      KERNEL_VERSION: ${{ inputs.KERNEL_VERSION }}
      KERNEL_NAME: ${{ inputs.KERNEL_NAME }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_version: ${{ inputs.kernelsu_version }}
      SUSFS_ENABLED: ${{ inputs.SUSFS_ENABLED }}
      VFS_patch_ENABLED: ${{ inputs.VFS_patch_ENABLED }}
